### PR TITLE
feat: alarm component 생성

### PR DESCRIPTION
**Pull request by hochan222**
> What was wrong/why is this fix needed? (quick summary only)

알림창 레이아웃 나누기, 프로필 컴포넌트 구현 완료

> Issue number (if there is an associated issue)

none

> Anything else that could help us review it

none

### CODE REVIEW

**Review by jwon42 — APPROVED** [review]
기반이 잘 닦여지고 있네요 👍

**Comment by hochan222** [comment]
@jwon42 핳ㅎ draft였는데 리뷰해주셨네요! 프로필 완성했습니댜 ㅎㅎ
image

**Review by yhshin0 — APPROVED** [review]

**Review by yechoi42 — APPROVED** [review]
👍

**Review by jwon42 — COMMENTED** [review]
👍

**Pull request closed without merging**
